### PR TITLE
Relaunch map instantiation if new metadata required from styles

### PR DESCRIPTION
**Pull request by VictorVelarde**
If a new style is set, with Layer.setStyle, that requires a new column, we're not reinstantiating the map (vector map in maps api, aka source.init), but we should, or it will crash. Something similar can happen if we require more columns in a popup after the first instantiation

### CODE REVIEW

**Comment by simon-contreras-deel** [comment]
**style is changed after layer was added to deck**:
- [x] create new deck layer

**popup is added after layer was added to deck**:
- [x] layer calls source.init after setting a popup
- [x] Sources does nothing if the fields do not change or send a warning (instead of the current error in CARTOSource)

**Comment by simon-contreras-deel** [comment]
@VictorVelarde it is ready to be reviewed

**Comment by simon-contreras-deel** [comment]
Again in review. An example file has been created to help in validation `examples/_debug/source/reinstantiation.html`. The idea is to play adding styles, popups and so after the layer is added to deck.

**Comment by VictorVelarde** [comment]
I'll see the conflict and CR

**Review by VictorVelarde — COMMENTED** [review]
Nice work and testing.

Please @simon check the conflict and also update the branch examples to beta.1. Then IMO we're ready to go (but you'll have to approve it, as I was the original creator... 😄 )

**Comment by simon-contreras-deel** [comment]
Rebasing it...

**Review by simon-contreras-deel — APPROVED** [review]
Self-approve :)

**Pull request merged**
