### PR TITLE
Geojson source

### PR DESCRIPTION
**Pull request by simon-contreras-deel**
Adding geoJson source support

**It needs https://github.com/CartoDB/web-sdk/pull/15 merged (deck.gl version) to work properly with point layers**

Examples:
- https://web-sdk-git-geojson-source.carto-frontend.vercel.app/examples/layer/geojson.html
- Styles: https://web-sdk-git-geojson-source.carto-frontend.vercel.app/examples/_debug/geojson

### CODE REVIEW

**Comment by VictorVelarde** [comment]
I'm having a look at the conflicts now... 🔝

**Comment by simon-contreras-deel** [comment]
Thank you for solving conflicts. Shall we merge it up?

**Comment by VictorVelarde** [comment]
Great job, I have exposed the source in the api, and also I promoted the most basic example to the public docs

**Review by VictorVelarde — APPROVED** [review]
🚀 go, go, go

**Pull request merged**
