### PR TITLE
Add position property to Popup constructor

### PR DESCRIPTION
**Pull request by sclebal**

### CODE REVIEW

**Review by manmorjim — COMMENTED** [review]
LGTM :ok_hand: 

Great improvement! This allows adapting popup to both left and right map edges. However, I miss `top` and `bottom` positions in order to allow popups to be adapted to whole viewport edges.

By this way, if the popup is close to a viewport corner this would be adapted. E.g. if the popup is close to the upper right corner then the position would be `left-bottom`:

image

I also miss a method to set the position for a popup already instantiated.

**Comment by sclebal** [comment]
@manmorjim check what I've just uploaded.

**Comment by manmorjim** [comment]
Nicee! :100: 

LGTM :ok_hand:

**Review by manmorjim — APPROVED** [review]

**Comment by VictorVelarde** [comment]
I see the result (and the potential for a future-better auto-positioning), but @Clebal could you please describe a bit your use case now, with this addition?

**Comment by sclebal** [comment]
@VictorVelarde There isn't an use case, it's something about design. Designers what the popup in the top-center and I need a way to achieve it.

**Comment by VictorVelarde** [comment]
Ok, that's enough for me. It's a fair design request.

**Comment by VictorVelarde** [comment]
@manmorjim please, have a last look and let's merge this one!

**Pull request merged**
