### PR TITLE
Update deck version to 8.2.0-alpha.2 and basic examples improvements

### PR DESCRIPTION
**Pull request by simon-contreras-deel**
- update deck.gl version to `8.2.0-alpha.2`
- use basic style helper as default layer style

Validation:
- before: https://web-sdk-git-develop.carto-frontend.now.sh/examples/_debug/styles/basic-style.html
- after: https://web-sdk-git-update-deck-version.carto-frontend.now.sh/examples/_debug/styles/basic-style.html

### CODE REVIEW

**Comment by VictorVelarde** [comment]
I'lll take this one. I have a WIP PR on examples refactor / improvements, and I would like them to be on sync

**Review by jesusbotella — APPROVED** [review]

**Comment by VictorVelarde** [comment]
Don't merge it yet, I'm gonna bring some work on examples here

**Review by VictorVelarde — APPROVED** [review]
🚀  (Examples were already on alpha.2, so we just missed the 'package.json). In any case, I added my WIP on some examples, even it's quite independent

**Comment by VictorVelarde** [comment]
I have rebased develop and force pushed. Setting pinned version to alpha.2

**Pull request merged**
