### PR TITLE
Add filters to GeoJSON Source

### PR DESCRIPTION
**Pull request by jesusbotella**
This PR adds the capability of retrieving filtered data from `.getFeatures` method with filters added manually or added from a widget.

### CODE REVIEW

**Comment by VictorVelarde** [comment]
Still relevant as it is now? or included in the other PR?

**Comment by VictorVelarde** [comment]
Ping me when it's ready. I'll have another quick look at it to approve it

**Comment by jesusbotella** [comment]
It's now ready! I have added tests for the filters as well.

**Review by VictorVelarde — APPROVED** [review]
Nice! Go ahead

**Pull request merged**
