### PR TITLE
Easy access isOpened property in Popup.

### PR DESCRIPTION
**Pull request by sclebal**
I've added a method in Popup to check if a popup is already opened or not. It's very useful.

### CODE REVIEW

**Review by manmorjim — COMMENTED** [review]
LGTM :ok_hand: 

Now Popup tests are available in `develop` it would be nice adding some tests for this method :blush:

**Comment by VictorVelarde** [comment]
I was going to suggest renaming the internal '_isOpened' variable to '_isOpen' and turn the function into a property, like this:

```
  /**
   * Whether the popup is open or not
   */
  public get isOpen() {
    return this._isOpen;
  }
```

**Comment by sclebal** [comment]
@VictorVelarde changed and updated with the fix of this task https://app.clubhouse.io/cartoteam/story/87541/popup-interactivity-glitch-when-cursor-hover-the-popup. It should work. Maybe I've should opened a different PR for the fix 🤦 sorry, the rush is not good.

**Review by VictorVelarde — APPROVED** [review]
LGTM. Let's merge this!

**Pull request merged**
